# .gitlab-ci.yml

stages:
  - build
  - test

variables:
  DJANGO_SETTINGS_MODULE: "TechNews_back.settings"

before_script:
  - pip3 install -r requirements.txt

migrations:
  stage: build
  script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py check

test:
  stage: test
  script:
    - python3 manage.py test
