# .gitlab-ci.yml
image: python:3.11

stages:
  - build
  - test

variables:
  DJANGO_SETTINGS_MODULE: "TechNews_back.settings"

before_script:
  - pip install -r requirements.txt

migrations:
  stage: build
  script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py check

test:
  stage: test
  script:
    - python manage.py test
